version: '3'
services:
  ph-salary-service:
    build:
      context: ./app
    depends_on:
      - jaeger-agent-service
    networks:
      - app_network

  jaeger-agent-service:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_PORT=14268
    networks:
      - app_network

networks:
  app_network:
    driver: bridge